name: ecommerce
description: E-Commerce Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  animated_text_kit: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  fonts:
     - family: SFProDisplay-Bold
       fonts:
         - asset: assets/fonts/FontsFree-Net-SFProDisplay-Bold.ttf

     - family: SFProDisplay-Regular
       fonts:
         - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf

